# Generated by Django 3.2.4 on 2021-07-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bodyTwo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
