# Generated by Django 3.2.4 on 2021-07-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210722_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('site', models.TextField()),
                ('explan', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
